<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies [
    <!ELEMENT movies (movie+)>
    <!ELEMENT movie (title,director,release_date,budget,duration?)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT release_date (#PCDATA)>
    <!ELEMENT budget (#PCDATA)>
    <!ELEMENT duration EMPTY>
    <!ATTLIST movie country CDATA #IMPLIED>
    <!ATTLIST duration minutes CDATA #REQUIRED>
]>
<movies>
    <movie country="US">
        <title>The Shawshank Redemption</title>
        <director>Frank Darabont</director>
        <release_date>1994-09-23</release_date>
        <budget>$25 million</budget>
        <duration minutes="142" />
    </movie>
    <movie country="UK">
        <title>Inception</title>
        <director>Christopher Nolan</director>
        <release_date>2010-07-16</release_date>
        <budget>$160 million</budget>
    </movie>
    <movie>
        <title>The Dark Knight</title>
        <director>Christopher Nolan</director>
        <release_date>2008-07-18</release_date>
        <budget>$185 million</budget>
        <duration minutes="152" />
    </movie>
    <movie country="US">
        <title>Avatar</title>
        <director>James Cameron</director>
        <release_date>2009-12-18</release_date>
        <budget>$237 million</budget>
        <duration minutes="162" />
    </movie>
    <movie country="US">
        <title>Rogue One: A Star Wars Story</title>
        <director>Gareth Edwards</director>
        <release_date>2016-12-16</release_date>
        <budget>$200 million</budget>
        <duration minutes="133" />
    </movie>
    <movie country="US">
        <title>Avengers: Endgame</title>
        <director>Anthony Russo, Joe Russo</director>
        <release_date>2019-04-26</release_date>
        <budget>$356 million</budget>
        <duration minutes="181" />
    </movie>
    <movie country="US">
        <title>Toy Story</title>
        <director>John Lasseter</director>
        <release_date>1995-11-22</release_date>
        <budget>$30 million</budget>
        <!-- <duration minutes="81"/> -->
    </movie>
</movies>